# Aula 02

## Dados Numericos 

In [7]:
# Variável Inteira

a = 1

print("Valor de a ="+str(a))

type(a)

Valor de a =1


int

In [8]:
# Variável dupla precisão

b = 1.0
print(b)
type(b)

1.0


float

In [9]:
# Converter float para int 

c = int(b)
print(c)
type(c)


1


int

In [10]:
# Declarando nan
import numpy as np
d = np.nan
print(d)
type(d)


nan


float

In [13]:
# Operação com NaNe 

e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,e])
print(e)


nan
nan
0.0


## Dados de texto 

In [20]:
# Declaração de variável texto
f = "Fabio"
g = "gabriel"
print(f)
print(g)
print(f+g)
print(f+" "+g)


Fabio
gabriel
Fabiogabriel
Fabio gabriel


## Dados tipo Bool - lógica 

In [21]:
a == 1

True

In [23]:
h = (a==1)
print(h)
type(h)

True


bool

In [26]:
i = True
type(i)


bool

In [27]:
ii = "True"
type(ii)

str

# Operação de Comparação 



In [28]:
# Operacao com ==
a==b

True

In [29]:
# Operacao com >
a>b

False

In [30]:
# Operação com != (diferente)

In [31]:
a!=b

False

In [32]:
# Operação com >=

In [33]:
a>=b

True

# OPerações Matematicas 

In [36]:
# soma
a+b

2.0

In [38]:
# seoma e atribui

ab = a+b
print(a+b)

2.0


In [41]:
# Multiplicação
print("não use l como variável")
j = a*b
print(j)

não use l como variável
1.0


In [43]:
# Potencia 

5**2

25

In [45]:
# Operações matemáticas com a biblioteca math
import math

math.exp(10)

22026.465794806718

In [46]:
math.exp(a)

2.718281828459045

In [48]:
import math as mt
mt.log(c)

0.0

## Listas

In [50]:
myFirstList = (1,2,3)
print(myFirstList)

(1, 2, 3)


In [53]:
# Acessando valores da lista pelo index (para acessar a lista sempre colchete)
print(myFirstList[0])


1


In [57]:
mySecList = [1,a,"c"]
print(mySecList)

[1, 1, 'c']


In [58]:
type(mySecList)

list

# CAminhos = Path

In [61]:
path = r"C:\Users\conta\Documents\ENS\ENS410064"
print(path)

C:\Users\conta\Documents\ENS\ENS410064


In [62]:
path = "C:/Users/conta/Documents/ENS/ENS410064"

In [64]:
import os

#listar arquivos na pasta 
os.listdir(path)
os.listdir(path)[0]

'.git'

In [65]:
# Contatenando caminhos 
path+"/"+(os.listdir(path)[0])

'C:/Users/conta/Documents/ENS/ENS410064/.git'

In [67]:
#Listando caminhos concatenados
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [70]:
#Diretoria que estou trabalhando
os.getcwd()

'C:\\Users\\conta\\Documents\\ENS\\ENS410064\\pyenv\\Scripts'

In [75]:
# Criando um diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretorio ja existe')
else:
    print('criando diretorio')

criando diretorio


## Numpyarrays and pandas dataframe 

In [79]:
import numpy as np

n = np.array(0)
type(n)

numpy.ndarray

In [81]:
myThirdList=[1,2,3,10,20,50]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 50]


In [86]:
# Criando uma matriz de 10x10 de numeros entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matriz 
print(n.shape)

[[0.33812429 0.92984746 0.65171546 0.45164624 0.81801622 0.10375055
  0.08903499 0.15384306 0.97238414 0.30604859]
 [0.621416   0.89501959 0.53736899 0.99915578 0.51854226 0.98118213
  0.5182314  0.67937856 0.56972278 0.08424617]
 [0.32365432 0.36079508 0.08641734 0.25401039 0.41465071 0.86572335
  0.96084788 0.51277893 0.47536894 0.47649941]
 [0.22658651 0.70032935 0.12438125 0.47743484 0.79933435 0.2555344
  0.35848172 0.73408606 0.27228133 0.22211269]
 [0.42967479 0.79661391 0.07071214 0.26512517 0.57051708 0.55632167
  0.86991647 0.78320701 0.22325955 0.31736891]
 [0.55819726 0.6321894  0.80384467 0.01316359 0.6519657  0.38325554
  0.62178274 0.9197566  0.40250964 0.56182488]
 [0.06736721 0.91696854 0.49899193 0.52374836 0.43924324 0.05063533
  0.20285404 0.97367041 0.79151125 0.36217582]
 [0.86259172 0.33378876 0.04374818 0.01976915 0.71782305 0.24561884
  0.6759931  0.31505271 0.33181412 0.37049227]
 [0.21368532 0.21846434 0.050425   0.67442496 0.33312831 0.14790387
  0.19861281 

In [84]:
print(n.shape)

(10, 10)


In [89]:
# Acessando valores da matriz 

n[0,:]

array([0.33812429, 0.92984746, 0.65171546, 0.45164624, 0.81801622,
       0.10375055, 0.08903499, 0.15384306, 0.97238414, 0.30604859])

In [90]:
n[:,0]

array([0.33812429, 0.621416  , 0.32365432, 0.22658651, 0.42967479,
       0.55819726, 0.06736721, 0.86259172, 0.21368532, 0.98399817])

In [91]:
n[:,1:5]

array([[0.92984746, 0.65171546, 0.45164624, 0.81801622],
       [0.89501959, 0.53736899, 0.99915578, 0.51854226],
       [0.36079508, 0.08641734, 0.25401039, 0.41465071],
       [0.70032935, 0.12438125, 0.47743484, 0.79933435],
       [0.79661391, 0.07071214, 0.26512517, 0.57051708],
       [0.6321894 , 0.80384467, 0.01316359, 0.6519657 ],
       [0.91696854, 0.49899193, 0.52374836, 0.43924324],
       [0.33378876, 0.04374818, 0.01976915, 0.71782305],
       [0.21846434, 0.050425  , 0.67442496, 0.33312831],
       [0.45477069, 0.59064257, 0.35785437, 0.17135219]])

In [93]:
# Linha e coluna 
n[1,1]

0.8950195935504572

In [94]:
n[0,:]

array([0.33812429, 0.92984746, 0.65171546, 0.45164624, 0.81801622,
       0.10375055, 0.08903499, 0.15384306, 0.97238414, 0.30604859])

In [95]:
an = np.log(n)
print(an)

[[-1.08434173e+00 -7.27347311e-02 -4.28147227e-01 -7.94856071e-01
  -2.00873116e-01 -2.26576584e+00 -2.41872579e+00 -1.87182226e+00
  -2.80043462e-02 -1.18401141e+00]
 [-4.75754537e-01 -1.10909669e-01 -6.21070280e-01 -8.44574376e-04
  -6.56733749e-01 -1.89971805e-02 -6.57333427e-01 -3.86576785e-01
  -5.62605386e-01 -2.47401222e+00]
 [-1.12807924e+00 -1.01944512e+00 -2.44856689e+00 -1.37038012e+00
  -8.80318770e-01 -1.44189874e-01 -3.99391766e-02 -6.67910468e-01
  -7.43664053e-01 -7.41288789e-01]
 [-1.48462848e+00 -3.56204554e-01 -2.08440387e+00 -7.39327595e-01
  -2.23975956e-01 -1.36439824e+00 -1.02587762e+00 -3.09129012e-01
  -1.30091944e+00 -1.50457043e+00]
 [-8.44726666e-01 -2.27385152e-01 -2.64913803e+00 -1.32755324e+00
  -5.61212172e-01 -5.86408614e-01 -1.39358078e-01 -2.44358232e-01
  -1.49942026e+00 -1.14769042e+00]
 [-5.83042875e-01 -4.58566244e-01 -2.18349222e-01 -4.33030044e+00
  -4.27763321e-01 -9.59053317e-01 -4.75164535e-01 -8.36462092e-02
  -9.10036228e-01 -5.76565072e-01